# Generated by Django 4.2.3 on 2023-07-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("things", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anything", models.CharField(max_length=255)),
            ],
        ),
    ]
